# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.18.5" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.18.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.18.5.tgz";
        sha512 = "YZWVaglMiplo7v8f1oMQ5ZPQr0vn7HPeZXxXWsxXJRjGVrzUFn9OxFQl1sb5wzfootjA/yChhW84BV+383FSOw==";
      };
    };
    "@intlify/core-base-9.1.10" = {
      name = "_at_intlify_slash_core-base";
      packageName = "@intlify/core-base";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@intlify/core-base/-/core-base-9.1.10.tgz";
        sha512 = "So9CNUavB/IsZ+zBmk2Cv6McQp6vc2wbGi1S0XQmJ8Vz+UFcNn9MFXAe9gY67PreIHrbLsLxDD0cwo1qsxM1Nw==";
      };
    };
    "@intlify/devtools-if-9.1.10" = {
      name = "_at_intlify_slash_devtools-if";
      packageName = "@intlify/devtools-if";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@intlify/devtools-if/-/devtools-if-9.1.10.tgz";
        sha512 = "SHaKoYu6sog3+Q8js1y3oXLywuogbH1sKuc7NSYkN3GElvXSBaMoCzW+we0ZSFqj/6c7vTNLg9nQ6rxhKqYwnQ==";
      };
    };
    "@intlify/message-compiler-9.1.10" = {
      name = "_at_intlify_slash_message-compiler";
      packageName = "@intlify/message-compiler";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@intlify/message-compiler/-/message-compiler-9.1.10.tgz";
        sha512 = "+JiJpXff/XTb0EadYwdxOyRTB0hXNd4n1HaJ/a4yuV960uRmPXaklJsedW0LNdcptd/hYUZtCkI7Lc9J5C1gxg==";
      };
    };
    "@intlify/message-resolver-9.1.10" = {
      name = "_at_intlify_slash_message-resolver";
      packageName = "@intlify/message-resolver";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@intlify/message-resolver/-/message-resolver-9.1.10.tgz";
        sha512 = "5YixMG/M05m0cn9+gOzd4EZQTFRUu8RGhzxJbR1DWN21x/Z3bJ8QpDYj6hC4FwBj5uKsRfKpJQ3Xqg98KWoA+w==";
      };
    };
    "@intlify/runtime-9.1.10" = {
      name = "_at_intlify_slash_runtime";
      packageName = "@intlify/runtime";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@intlify/runtime/-/runtime-9.1.10.tgz";
        sha512 = "7QsuByNzpe3Gfmhwq6hzgXcMPpxz8Zxb/XFI6s9lQdPLPe5Lgw4U1ovRPZTOs6Y2hwitR3j/HD8BJNGWpJnOFA==";
      };
    };
    "@intlify/shared-9.1.10" = {
      name = "_at_intlify_slash_shared";
      packageName = "@intlify/shared";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@intlify/shared/-/shared-9.1.10.tgz";
        sha512 = "Om54xJeo1Vw+K1+wHYyXngE8cAbrxZHpWjYzMR9wCkqbhGtRV5VLhVc214Ze2YatPrWlS2WSMOWXR8JktX/IgA==";
      };
    };
    "@intlify/vue-devtools-9.1.10" = {
      name = "_at_intlify_slash_vue-devtools";
      packageName = "@intlify/vue-devtools";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@intlify/vue-devtools/-/vue-devtools-9.1.10.tgz";
        sha512 = "5l3qYARVbkWAkagLu1XbDUWRJSL8br1Dj60wgMaKB0+HswVsrR6LloYZTg7ozyvM621V6+zsmwzbQxbVQyrytQ==";
      };
    };
    "@quasar/extras-1.14.0" = {
      name = "_at_quasar_slash_extras";
      packageName = "@quasar/extras";
      version = "1.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@quasar/extras/-/extras-1.14.0.tgz";
        sha512 = "4qVLqiKHV8tpvj/VgyxI5FlWCwQvWQzq15xlLeCDpzLOGeJruUXs+QCAB5gFgdDHPbU2ax2YgAxyGoQSCS7ACw==";
      };
    };
    "@quasar/vite-plugin-1.0.10" = {
      name = "_at_quasar_slash_vite-plugin";
      packageName = "@quasar/vite-plugin";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@quasar/vite-plugin/-/vite-plugin-1.0.10.tgz";
        sha512 = "2RTaBQj5RppUS/lOH/ZdeCThO2OeTTh0g9dsDJ59YGzzg0nYBYRhJ0daKPuOYeWUsaHpJFwEP68aXHQPuzCBOA==";
      };
    };
    "@sphinxxxx/color-conversion-2.2.2" = {
      name = "_at_sphinxxxx_slash_color-conversion";
      packageName = "@sphinxxxx/color-conversion";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sphinxxxx/color-conversion/-/color-conversion-2.2.2.tgz";
        sha512 = "XExJS3cLqgrmNBIP3bBw6+1oQ1ksGjFh0+oClDKFYpCCqx/hlqwWO5KO/S63fzUo67SxI9dMrF0y5T/Ey7h8Zw==";
      };
    };
    "@types/eslint-8.4.2" = {
      name = "_at_types_slash_eslint";
      packageName = "@types/eslint";
      version = "8.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/eslint/-/eslint-8.4.2.tgz";
        sha512 = "Z1nseZON+GEnFjJc04sv4NSALGjhFwy6K0HXt7qsn5ArfAKtb63dXNJHf+1YW6IpOIYRBGUbu3GwJdj8DGnCjA==";
      };
    };
    "@types/eslint-scope-3.7.3" = {
      name = "_at_types_slash_eslint-scope";
      packageName = "@types/eslint-scope";
      version = "3.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/eslint-scope/-/eslint-scope-3.7.3.tgz";
        sha512 = "PB3ldyrcnAicT35TWPs5IcwKD8S333HMaa2VVv4+wdvebJkjWuW/xESoB8IwRcog8HYVYamb1g/R31Qv5Bx03g==";
      };
    };
    "@types/estree-0.0.51" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "0.0.51";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-0.0.51.tgz";
        sha512 = "CuPgU6f3eT/XgKKPqKd/gLZV1Xmvf1a2R5POBOGQa6uv82xpls89HU5zKeVoyR8XzHd1RGNOlQlvUe3CFkjWNQ==";
      };
    };
    "@types/js-cookie-3.0.2" = {
      name = "_at_types_slash_js-cookie";
      packageName = "@types/js-cookie";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/js-cookie/-/js-cookie-3.0.2.tgz";
        sha512 = "6+0ekgfusHftJNYpihfkMu8BWdeHs9EOJuGcSofErjstGPfPGEu9yTu4t460lTzzAMl2cM5zngQJqPMHbbnvYA==";
      };
    };
    "@types/json-schema-7.0.11" = {
      name = "_at_types_slash_json-schema";
      packageName = "@types/json-schema";
      version = "7.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.11.tgz";
        sha512 = "wOuvG1SN4Us4rez+tylwwwCV1psiNVOkJeM3AUWUNWg/jDQY2+HE/444y5gc+jBmRqASOm2Oeh5c1axHobwRKQ==";
      };
    };
    "@types/node-17.0.32" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.32.tgz";
        sha512 = "eAIcfAvhf/BkHcf4pkLJ7ECpBAhh9kcxRBpip9cTiO+hf+aJrsxYxBeS6OXvOd9WqNAJmavXVpZvY1rBjNsXmw==";
      };
    };
    "@vitejs/plugin-vue-2.3.3" = {
      name = "_at_vitejs_slash_plugin-vue";
      packageName = "@vitejs/plugin-vue";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vitejs/plugin-vue/-/plugin-vue-2.3.3.tgz";
        sha512 = "SmQLDyhz+6lGJhPELsBdzXGc+AcaT8stgkbiTFGpXPe8Tl1tJaBw1A6pxDqDuRsVkD8uscrkx3hA7QDOoKYtyw==";
      };
    };
    "@volar/code-gen-0.38.1" = {
      name = "_at_volar_slash_code-gen";
      packageName = "@volar/code-gen";
      version = "0.38.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/code-gen/-/code-gen-0.38.1.tgz";
        sha512 = "QnEJfCPhPqzhQY/iN7euGoUWphyv4TmN1xK/HEpnXwgqgvIyLk/Ih3rvAFqlP6I5fTaCu6TGf9kZmjw9AlEeMA==";
      };
    };
    "@volar/source-map-0.38.1" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "0.38.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-0.38.1.tgz";
        sha512 = "1DoB8BYTle81DdLChnurYteN208qvsfz4IgwjH6T2YcnBtUvtscxMOwg0bfQJskfoLrJ5gESBvEpU8tWsEVyrQ==";
      };
    };
    "@volar/vue-code-gen-0.38.1" = {
      name = "_at_volar_slash_vue-code-gen";
      packageName = "@volar/vue-code-gen";
      version = "0.38.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-code-gen/-/vue-code-gen-0.38.1.tgz";
        sha512 = "tgJ2uySZKZqiq6HFKmjeVmUhJttd2LMhqtlqSukdqGx2Xw/OWnL0Di7+q6AScC6tu9/Bw570HKMHbhhLIrQm2Q==";
      };
    };
    "@volar/vue-typescript-0.38.1" = {
      name = "_at_volar_slash_vue-typescript";
      packageName = "@volar/vue-typescript";
      version = "0.38.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-typescript/-/vue-typescript-0.38.1.tgz";
        sha512 = "D4bTuiJ2WiRppJuZ34r3pstFLTwpweke3haszJwp0ioUI9BqKgh02TFqM+qhPezH6fF0NrWCxXMMQVxZL6d7gA==";
      };
    };
    "@vue/compiler-core-3.2.37" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.2.37.tgz";
        sha512 = "81KhEjo7YAOh0vQJoSmAD68wLfYqJvoiD4ulyedzF+OEk/bk6/hx3fTNVfuzugIIaTrOx4PGx6pAiBRe5e9Zmg==";
      };
    };
    "@vue/compiler-dom-3.2.37" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.2.37.tgz";
        sha512 = "yxJLH167fucHKxaqXpYk7x8z7mMEnXOw3G2q62FTkmsvNxu4FQSu5+3UMb+L7fjKa26DEzhrmCxAgFLLIzVfqQ==";
      };
    };
    "@vue/compiler-sfc-3.2.37" = {
      name = "_at_vue_slash_compiler-sfc";
      packageName = "@vue/compiler-sfc";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-sfc/-/compiler-sfc-3.2.37.tgz";
        sha512 = "+7i/2+9LYlpqDv+KTtWhOZH+pa8/HnX/905MdVmAcI/mPQOBwkHHIzrsEsucyOIZQYMkXUiTkmZq5am/NyXKkg==";
      };
    };
    "@vue/compiler-ssr-3.2.37" = {
      name = "_at_vue_slash_compiler-ssr";
      packageName = "@vue/compiler-ssr";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-ssr/-/compiler-ssr-3.2.37.tgz";
        sha512 = "7mQJD7HdXxQjktmsWp/J67lThEIcxLemz1Vb5I6rYJHR5vI+lON3nPGOH3ubmbvYGt8xEUaAr1j7/tIFWiEOqw==";
      };
    };
    "@vue/devtools-api-6.1.4" = {
      name = "_at_vue_slash_devtools-api";
      packageName = "@vue/devtools-api";
      version = "6.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/devtools-api/-/devtools-api-6.1.4.tgz";
        sha512 = "IiA0SvDrJEgXvVxjNkHPFfDx6SXw0b/TUkqMcDZWNg9fnCAHbTpoo59YfJ9QLFkwa3raau5vSlRVzMSLDnfdtQ==";
      };
    };
    "@vue/reactivity-3.2.37" = {
      name = "_at_vue_slash_reactivity";
      packageName = "@vue/reactivity";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity/-/reactivity-3.2.37.tgz";
        sha512 = "/7WRafBOshOc6m3F7plwzPeCu/RCVv9uMpOwa/5PiY1Zz+WLVRWiy0MYKwmg19KBdGtFWsmZ4cD+LOdVPcs52A==";
      };
    };
    "@vue/reactivity-transform-3.2.37" = {
      name = "_at_vue_slash_reactivity-transform";
      packageName = "@vue/reactivity-transform";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity-transform/-/reactivity-transform-3.2.37.tgz";
        sha512 = "IWopkKEb+8qpu/1eMKVeXrK0NLw9HicGviJzhJDEyfxTR9e1WtpnnbYkJWurX6WwoFP0sz10xQg8yL8lgskAZg==";
      };
    };
    "@vue/runtime-core-3.2.37" = {
      name = "_at_vue_slash_runtime-core";
      packageName = "@vue/runtime-core";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/runtime-core/-/runtime-core-3.2.37.tgz";
        sha512 = "JPcd9kFyEdXLl/i0ClS7lwgcs0QpUAWj+SKX2ZC3ANKi1U4DOtiEr6cRqFXsPwY5u1L9fAjkinIdB8Rz3FoYNQ==";
      };
    };
    "@vue/runtime-dom-3.2.37" = {
      name = "_at_vue_slash_runtime-dom";
      packageName = "@vue/runtime-dom";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/runtime-dom/-/runtime-dom-3.2.37.tgz";
        sha512 = "HimKdh9BepShW6YozwRKAYjYQWg9mQn63RGEiSswMbW+ssIht1MILYlVGkAGGQbkhSh31PCdoUcfiu4apXJoPw==";
      };
    };
    "@vue/server-renderer-3.2.37" = {
      name = "_at_vue_slash_server-renderer";
      packageName = "@vue/server-renderer";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/server-renderer/-/server-renderer-3.2.37.tgz";
        sha512 = "kLITEJvaYgZQ2h47hIzPh2K3jG8c1zCVbp/o/bzQOyvzaKiCquKS7AaioPI28GNxIsE/zSx+EwWYsNxDCX95MA==";
      };
    };
    "@vue/shared-3.2.37" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.2.37.tgz";
        sha512 = "4rSJemR2NQIo9Klm1vabqWjD8rs/ZaJSzMxkMNeJS6lHiUjjUeYFbooN19NgFjztubEKh3WlZUeOLVdbbUWHsw==";
      };
    };
    "@webassemblyjs/ast-1.11.1" = {
      name = "_at_webassemblyjs_slash_ast";
      packageName = "@webassemblyjs/ast";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/ast/-/ast-1.11.1.tgz";
        sha512 = "ukBh14qFLjxTQNTXocdyksN5QdM28S1CxHt2rdskFyL+xFV7VremuBLVbmCePj+URalXBENx/9Lm7lnhihtCSw==";
      };
    };
    "@webassemblyjs/floating-point-hex-parser-1.11.1" = {
      name = "_at_webassemblyjs_slash_floating-point-hex-parser";
      packageName = "@webassemblyjs/floating-point-hex-parser";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/floating-point-hex-parser/-/floating-point-hex-parser-1.11.1.tgz";
        sha512 = "iGRfyc5Bq+NnNuX8b5hwBrRjzf0ocrJPI6GWFodBFzmFnyvrQ83SHKhmilCU/8Jv67i4GJZBMhEzltxzcNagtQ==";
      };
    };
    "@webassemblyjs/helper-api-error-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-api-error";
      packageName = "@webassemblyjs/helper-api-error";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-api-error/-/helper-api-error-1.11.1.tgz";
        sha512 = "RlhS8CBCXfRUR/cwo2ho9bkheSXG0+NwooXcc3PAILALf2QLdFyj7KGsKRbVc95hZnhnERon4kW/D3SZpp6Tcg==";
      };
    };
    "@webassemblyjs/helper-buffer-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-buffer";
      packageName = "@webassemblyjs/helper-buffer";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-buffer/-/helper-buffer-1.11.1.tgz";
        sha512 = "gwikF65aDNeeXa8JxXa2BAk+REjSyhrNC9ZwdT0f8jc4dQQeDQ7G4m0f2QCLPJiMTTO6wfDmRmj/pW0PsUvIcA==";
      };
    };
    "@webassemblyjs/helper-numbers-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-numbers";
      packageName = "@webassemblyjs/helper-numbers";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-numbers/-/helper-numbers-1.11.1.tgz";
        sha512 = "vDkbxiB8zfnPdNK9Rajcey5C0w+QJugEglN0of+kmO8l7lDb77AnlKYQF7aarZuCrv+l0UvqL+68gSDr3k9LPQ==";
      };
    };
    "@webassemblyjs/helper-wasm-bytecode-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-wasm-bytecode";
      packageName = "@webassemblyjs/helper-wasm-bytecode";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-wasm-bytecode/-/helper-wasm-bytecode-1.11.1.tgz";
        sha512 = "PvpoOGiJwXeTrSf/qfudJhwlvDQxFgelbMqtq52WWiXC6Xgg1IREdngmPN3bs4RoO83PnL/nFrxucXj1+BX62Q==";
      };
    };
    "@webassemblyjs/helper-wasm-section-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-wasm-section";
      packageName = "@webassemblyjs/helper-wasm-section";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-wasm-section/-/helper-wasm-section-1.11.1.tgz";
        sha512 = "10P9No29rYX1j7F3EVPX3JvGPQPae+AomuSTPiF9eBQeChHI6iqjMIwR9JmOJXwpnn/oVGDk7I5IlskuMwU/pg==";
      };
    };
    "@webassemblyjs/ieee754-1.11.1" = {
      name = "_at_webassemblyjs_slash_ieee754";
      packageName = "@webassemblyjs/ieee754";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/ieee754/-/ieee754-1.11.1.tgz";
        sha512 = "hJ87QIPtAMKbFq6CGTkZYJivEwZDbQUgYd3qKSadTNOhVY7p+gfP6Sr0lLRVTaG1JjFj+r3YchoqRYxNH3M0GQ==";
      };
    };
    "@webassemblyjs/leb128-1.11.1" = {
      name = "_at_webassemblyjs_slash_leb128";
      packageName = "@webassemblyjs/leb128";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/leb128/-/leb128-1.11.1.tgz";
        sha512 = "BJ2P0hNZ0u+Th1YZXJpzW6miwqQUGcIHT1G/sf72gLVD9DZ5AdYTqPNbHZh6K1M5VmKvFXwGSWZADz+qBWxeRw==";
      };
    };
    "@webassemblyjs/utf8-1.11.1" = {
      name = "_at_webassemblyjs_slash_utf8";
      packageName = "@webassemblyjs/utf8";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/utf8/-/utf8-1.11.1.tgz";
        sha512 = "9kqcxAEdMhiwQkHpkNiorZzqpGrodQQ2IGrHHxCy+Ozng0ofyMA0lTqiLkVs1uzTRejX+/O0EOT7KxqVPuXosQ==";
      };
    };
    "@webassemblyjs/wasm-edit-1.11.1" = {
      name = "_at_webassemblyjs_slash_wasm-edit";
      packageName = "@webassemblyjs/wasm-edit";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-edit/-/wasm-edit-1.11.1.tgz";
        sha512 = "g+RsupUC1aTHfR8CDgnsVRVZFJqdkFHpsHMfJuWQzWU3tvnLC07UqHICfP+4XyL2tnr1amvl1Sdp06TnYCmVkA==";
      };
    };
    "@webassemblyjs/wasm-gen-1.11.1" = {
      name = "_at_webassemblyjs_slash_wasm-gen";
      packageName = "@webassemblyjs/wasm-gen";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-gen/-/wasm-gen-1.11.1.tgz";
        sha512 = "F7QqKXwwNlMmsulj6+O7r4mmtAlCWfO/0HdgOxSklZfQcDu0TpLiD1mRt/zF25Bk59FIjEuGAIyn5ei4yMfLhA==";
      };
    };
    "@webassemblyjs/wasm-opt-1.11.1" = {
      name = "_at_webassemblyjs_slash_wasm-opt";
      packageName = "@webassemblyjs/wasm-opt";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-opt/-/wasm-opt-1.11.1.tgz";
        sha512 = "VqnkNqnZlU5EB64pp1l7hdm3hmQw7Vgqa0KF/KCNO9sIpI6Fk6brDEiX+iCOYrvMuBWDws0NkTOxYEb85XQHHw==";
      };
    };
    "@webassemblyjs/wasm-parser-1.11.1" = {
      name = "_at_webassemblyjs_slash_wasm-parser";
      packageName = "@webassemblyjs/wasm-parser";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-parser/-/wasm-parser-1.11.1.tgz";
        sha512 = "rrBujw+dJu32gYB7/Lup6UhdkPx9S9SnobZzRVL7VcBH9Bt9bCBLEuX/YXOOtBsOZ4NQrRykKhffRWHvigQvOA==";
      };
    };
    "@webassemblyjs/wast-printer-1.11.1" = {
      name = "_at_webassemblyjs_slash_wast-printer";
      packageName = "@webassemblyjs/wast-printer";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wast-printer/-/wast-printer-1.11.1.tgz";
        sha512 = "IQboUWM4eKzWW+N/jij2sRatKMh99QEelo3Eb2q0qXkvPRISAj8Qxtmw5itwqK+TTkBuUIE45AxYPToqPtL5gg==";
      };
    };
    "@xtuc/ieee754-1.2.0" = {
      name = "_at_xtuc_slash_ieee754";
      packageName = "@xtuc/ieee754";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xtuc/ieee754/-/ieee754-1.2.0.tgz";
        sha512 = "DX8nKgqcGwsc0eJSqYt5lwP4DH5FlHnmuWWBRy7X0NcaGR0ZtuyeESgMwTYVEtxmsNGY+qit4QYT/MIYTOTPeA==";
      };
    };
    "@xtuc/long-4.2.2" = {
      name = "_at_xtuc_slash_long";
      packageName = "@xtuc/long";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xtuc/long/-/long-4.2.2.tgz";
        sha512 = "NuHqBY1PB/D8xU6s/thBgOAiAP7HOYDQ32+BFZILJ8ivkUkAHQnWfn6WhL79Owj1qmUnoN/YPhktdIoucipkAQ==";
      };
    };
    "ace-builds-1.6.0" = {
      name = "ace-builds";
      packageName = "ace-builds";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ace-builds/-/ace-builds-1.6.0.tgz";
        sha512 = "qdkx965G/TA12IK7Zk+iCVDtA9wvhxIGivGc2rsID4UYbY2Bpatwep3ZrBZwj1IB2miU6FodDMqM9Kc1lqDlLg==";
      };
    };
    "acorn-8.7.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.7.1.tgz";
        sha512 = "Xx54uLJQZ19lKygFXOWsscKUbsBZW0CPykPhVQdhIeIwrbPmJzqeASDInc8nKBnp/JT6igTs82qPXz069H8I/A==";
      };
    };
    "acorn-import-assertions-1.8.0" = {
      name = "acorn-import-assertions";
      packageName = "acorn-import-assertions";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-import-assertions/-/acorn-import-assertions-1.8.0.tgz";
        sha512 = "m7VZ3jwz4eK6A4Vtt8Ew1/mNbP24u0FhdyfA7fSvnJR6LMdfOYnmuIrrJAgrYfYJ10F/otaHTtrtrtmHdMNzEw==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "ajv-keywords-3.5.2" = {
      name = "ajv-keywords";
      packageName = "ajv-keywords";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-keywords/-/ajv-keywords-3.5.2.tgz";
        sha512 = "5p6WTN0DdTGVQk6VjcEju19IgaHudalcfabD7yhDGeA6bcQnmL+CpveLJq/3hvfwd1aof6L386Ougkx6RfyMIQ==";
      };
    };
    "anymatch-3.1.2" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.2.tgz";
        sha512 = "P43ePfOAIupkguHUycrc4qJ9kz8ZiuOUijaETwX7THt0Y/GNK7v0aa8rY816xWjZ7rJdA5XdMcpVFTKMq+RvWg==";
      };
    };
    "apexcharts-3.35.3" = {
      name = "apexcharts";
      packageName = "apexcharts";
      version = "3.35.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/apexcharts/-/apexcharts-3.35.3.tgz";
        sha512 = "UDlxslJr3DG63I/SgoiivIu4lpP25GMaKFK8NvCHmTksTQshx4ng3oPPrYvdsBFOvD/ajPYIh/p7rNB0jq8vXg==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "axios-0.27.2" = {
      name = "axios";
      packageName = "axios";
      version = "0.27.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.27.2.tgz";
        sha512 = "t+yRIyySRTp/wua5xEr+z1q60QmLq8ABsS5O9Me1AsE5dfKqgnCFzwiCZZ/cGNd1lq4/7akDWMxdhVlucjmnOQ==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "big.js-5.2.2" = {
      name = "big.js";
      packageName = "big.js";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/big.js/-/big.js-5.2.2.tgz";
        sha512 = "vyL2OymJxmarO8gxMr0mhChsO9QGwhynfuu4+MHTAW6czfq9humCB7rKpUjDd9YUiDPU4mzpyupFSvOClAwbmQ==";
      };
    };
    "binary-extensions-2.2.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.2.0.tgz";
        sha512 = "jDctJ/IVQbZoJykoeHbhXpOlNBqGNcwXJKJog42E5HDPUwQTSdjCHdihjj0DlnheQ7blbT6dHOafNAiS8ooQKA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "browserslist-4.20.3" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.20.3.tgz";
        sha512 = "NBhymBQl1zM0Y5dQT/O+xiLP9/rzOIQdKM/eMJBAq7yBgaB6krIYLGejrwVYnSHZdqjscB1SPuAjHwxjvN6Wdg==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "caniuse-lite-1.0.30001340" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001340";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001340.tgz";
        sha512 = "jUNz+a9blQTQVu4uFcn17uAD8IDizPzQkIKh3LCJfg9BkyIqExYYdyc/ZSlWUSKb8iYiXxKsxbv4zYSvkqjrxw==";
      };
    };
    "chokidar-3.5.3" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.5.3.tgz";
        sha512 = "Dr3sfKRP6oTcjf2JmUmFJfeVMvXBdegxB0iVQ5eb2V10uFJUCAS8OByZdVAyVb8xXNz3GjjTgj9kLWsZTqE6kw==";
      };
    };
    "chrome-trace-event-1.0.3" = {
      name = "chrome-trace-event";
      packageName = "chrome-trace-event";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-trace-event/-/chrome-trace-event-1.0.3.tgz";
        sha512 = "p3KULyQg4S7NIHixdwbGX+nFHkoBiA4YQmyWtjb8XngSKV124nJmRysgAeujbUVb15vh+RvFUfCPqU7rXk+hZg==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "csstype-2.6.20" = {
      name = "csstype";
      packageName = "csstype";
      version = "2.6.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-2.6.20.tgz";
        sha512 = "/WwNkdXfckNgw6S5R125rrW8ez139lBHWouiBvX8dfMFtcn6V81REDqnH7+CRpRipfYlyU1CmOnOxrmGcFOjeA==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "electron-to-chromium-1.4.137" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.4.137";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.137.tgz";
        sha512 = "0Rcpald12O11BUogJagX3HsCN3FE83DSqWjgXoHo5a72KUKMSfI39XBgJpgNNxS9fuGzytaFjE06kZkiVFy2qA==";
      };
    };
    "emojis-list-3.0.0" = {
      name = "emojis-list";
      packageName = "emojis-list";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz";
        sha512 = "/kyM18EfinwXZbno9FyUGeFh87KC8HRQBQGildHZbEuRyWFOmv1U10o9BBp8XVZDVNNuQKyIGIu5ZYAAXJ0V2Q==";
      };
    };
    "enhanced-resolve-5.9.3" = {
      name = "enhanced-resolve";
      packageName = "enhanced-resolve";
      version = "5.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-5.9.3.tgz";
        sha512 = "Bq9VSor+kjvW3f9/MiiR4eE3XYgOl7/rS8lnSxbRbF3kS0B2r+Y9w5krBWxZgDxASVZbdYrn5wT4j/Wb0J9qow==";
      };
    };
    "es-module-lexer-0.9.3" = {
      name = "es-module-lexer";
      packageName = "es-module-lexer";
      version = "0.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-module-lexer/-/es-module-lexer-0.9.3.tgz";
        sha512 = "1HQ2M2sPtxwnvOvT1ZClHyQDiggdNjURWpY2we6aMKCQiUVxTmVs2UYPLIrD84sS+kMdUwfBSylbJPwNnBrnHQ==";
      };
    };
    "esbuild-0.14.39" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.14.39.tgz";
        sha512 = "2kKujuzvRWYtwvNjYDY444LQIA3TyJhJIX3Yo4+qkFlDDtGlSicWgeHVJqMUP/2sSfH10PGwfsj+O2ro1m10xQ==";
      };
    };
    "esbuild-android-64-0.14.39" = {
      name = "esbuild-android-64";
      packageName = "esbuild-android-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-64/-/esbuild-android-64-0.14.39.tgz";
        sha512 = "EJOu04p9WgZk0UoKTqLId9VnIsotmI/Z98EXrKURGb3LPNunkeffqQIkjS2cAvidh+OK5uVrXaIP229zK6GvhQ==";
      };
    };
    "esbuild-android-arm64-0.14.39" = {
      name = "esbuild-android-arm64";
      packageName = "esbuild-android-arm64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-arm64/-/esbuild-android-arm64-0.14.39.tgz";
        sha512 = "+twajJqO7n3MrCz9e+2lVOnFplRsaGRwsq1KL/uOy7xK7QdRSprRQcObGDeDZUZsacD5gUkk6OiHiYp6RzU3CA==";
      };
    };
    "esbuild-darwin-64-0.14.39" = {
      name = "esbuild-darwin-64";
      packageName = "esbuild-darwin-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.14.39.tgz";
        sha512 = "ImT6eUw3kcGcHoUxEcdBpi6LfTRWaV6+qf32iYYAfwOeV+XaQ/Xp5XQIBiijLeo+LpGci9M0FVec09nUw41a5g==";
      };
    };
    "esbuild-darwin-arm64-0.14.39" = {
      name = "esbuild-darwin-arm64";
      packageName = "esbuild-darwin-arm64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.14.39.tgz";
        sha512 = "/fcQ5UhE05OiT+bW5v7/up1bDsnvaRZPJxXwzXsMRrr7rZqPa85vayrD723oWMT64dhrgWeA3FIneF8yER0XTw==";
      };
    };
    "esbuild-freebsd-64-0.14.39" = {
      name = "esbuild-freebsd-64";
      packageName = "esbuild-freebsd-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-64/-/esbuild-freebsd-64-0.14.39.tgz";
        sha512 = "oMNH8lJI4wtgN5oxuFP7BQ22vgB/e3Tl5Woehcd6i2r6F3TszpCnNl8wo2d/KvyQ4zvLvCWAlRciumhQg88+kQ==";
      };
    };
    "esbuild-freebsd-arm64-0.14.39" = {
      name = "esbuild-freebsd-arm64";
      packageName = "esbuild-freebsd-arm64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-arm64/-/esbuild-freebsd-arm64-0.14.39.tgz";
        sha512 = "1GHK7kwk57ukY2yI4ILWKJXaxfr+8HcM/r/JKCGCPziIVlL+Wi7RbJ2OzMcTKZ1HpvEqCTBT/J6cO4ZEwW4Ypg==";
      };
    };
    "esbuild-linux-32-0.14.39" = {
      name = "esbuild-linux-32";
      packageName = "esbuild-linux-32";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-32/-/esbuild-linux-32-0.14.39.tgz";
        sha512 = "g97Sbb6g4zfRLIxHgW2pc393DjnkTRMeq3N1rmjDUABxpx8SjocK4jLen+/mq55G46eE2TA0MkJ4R3SpKMu7dg==";
      };
    };
    "esbuild-linux-64-0.14.39" = {
      name = "esbuild-linux-64";
      packageName = "esbuild-linux-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.14.39.tgz";
        sha512 = "4tcgFDYWdI+UbNMGlua9u1Zhu0N5R6u9tl5WOM8aVnNX143JZoBZLpCuUr5lCKhnD0SCO+5gUyMfupGrHtfggQ==";
      };
    };
    "esbuild-linux-arm-0.14.39" = {
      name = "esbuild-linux-arm";
      packageName = "esbuild-linux-arm";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.14.39.tgz";
        sha512 = "t0Hn1kWVx5UpCzAJkKRfHeYOLyFnXwYynIkK54/h3tbMweGI7dj400D1k0Vvtj2u1P+JTRT9tx3AjtLEMmfVBQ==";
      };
    };
    "esbuild-linux-arm64-0.14.39" = {
      name = "esbuild-linux-arm64";
      packageName = "esbuild-linux-arm64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.14.39.tgz";
        sha512 = "23pc8MlD2D6Px1mV8GMglZlKgwgNKAO8gsgsLLcXWSs9lQsCYkIlMo/2Ycfo5JrDIbLdwgP8D2vpfH2KcBqrDQ==";
      };
    };
    "esbuild-linux-mips64le-0.14.39" = {
      name = "esbuild-linux-mips64le";
      packageName = "esbuild-linux-mips64le";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-mips64le/-/esbuild-linux-mips64le-0.14.39.tgz";
        sha512 = "epwlYgVdbmkuRr5n4es3B+yDI0I2e/nxhKejT9H0OLxFAlMkeQZxSpxATpDc9m8NqRci6Kwyb/SfmD1koG2Zuw==";
      };
    };
    "esbuild-linux-ppc64le-0.14.39" = {
      name = "esbuild-linux-ppc64le";
      packageName = "esbuild-linux-ppc64le";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.14.39.tgz";
        sha512 = "W/5ezaq+rQiQBThIjLMNjsuhPHg+ApVAdTz2LvcuesZFMsJoQAW2hutoyg47XxpWi7aEjJGrkS26qCJKhRn3QQ==";
      };
    };
    "esbuild-linux-riscv64-0.14.39" = {
      name = "esbuild-linux-riscv64";
      packageName = "esbuild-linux-riscv64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-riscv64/-/esbuild-linux-riscv64-0.14.39.tgz";
        sha512 = "IS48xeokcCTKeQIOke2O0t9t14HPvwnZcy+5baG13Z1wxs9ZrC5ig5ypEQQh4QMKxURD5TpCLHw2W42CLuVZaA==";
      };
    };
    "esbuild-linux-s390x-0.14.39" = {
      name = "esbuild-linux-s390x";
      packageName = "esbuild-linux-s390x";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-s390x/-/esbuild-linux-s390x-0.14.39.tgz";
        sha512 = "zEfunpqR8sMomqXhNTFEKDs+ik7HC01m3M60MsEjZOqaywHu5e5682fMsqOlZbesEAAaO9aAtRBsU7CHnSZWyA==";
      };
    };
    "esbuild-netbsd-64-0.14.39" = {
      name = "esbuild-netbsd-64";
      packageName = "esbuild-netbsd-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-netbsd-64/-/esbuild-netbsd-64-0.14.39.tgz";
        sha512 = "Uo2suJBSIlrZCe4E0k75VDIFJWfZy+bOV6ih3T4MVMRJh1lHJ2UyGoaX4bOxomYN3t+IakHPyEoln1+qJ1qYaA==";
      };
    };
    "esbuild-openbsd-64-0.14.39" = {
      name = "esbuild-openbsd-64";
      packageName = "esbuild-openbsd-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-openbsd-64/-/esbuild-openbsd-64-0.14.39.tgz";
        sha512 = "secQU+EpgUPpYjJe3OecoeGKVvRMLeKUxSMGHnK+aK5uQM3n1FPXNJzyz1LHFOo0WOyw+uoCxBYdM4O10oaCAA==";
      };
    };
    "esbuild-sunos-64-0.14.39" = {
      name = "esbuild-sunos-64";
      packageName = "esbuild-sunos-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-sunos-64/-/esbuild-sunos-64-0.14.39.tgz";
        sha512 = "qHq0t5gePEDm2nqZLb+35p/qkaXVS7oIe32R0ECh2HOdiXXkj/1uQI9IRogGqKkK+QjDG+DhwiUw7QoHur/Rwg==";
      };
    };
    "esbuild-windows-32-0.14.39" = {
      name = "esbuild-windows-32";
      packageName = "esbuild-windows-32";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-32/-/esbuild-windows-32-0.14.39.tgz";
        sha512 = "XPjwp2OgtEX0JnOlTgT6E5txbRp6Uw54Isorm3CwOtloJazeIWXuiwK0ONJBVb/CGbiCpS7iP2UahGgd2p1x+Q==";
      };
    };
    "esbuild-windows-64-0.14.39" = {
      name = "esbuild-windows-64";
      packageName = "esbuild-windows-64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.14.39.tgz";
        sha512 = "E2wm+5FwCcLpKsBHRw28bSYQw0Ikxb7zIMxw3OPAkiaQhLVr3dnVO8DofmbWhhf6b97bWzg37iSZ45ZDpLw7Ow==";
      };
    };
    "esbuild-windows-arm64-0.14.39" = {
      name = "esbuild-windows-arm64";
      packageName = "esbuild-windows-arm64";
      version = "0.14.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-arm64/-/esbuild-windows-arm64-0.14.39.tgz";
        sha512 = "sBZQz5D+Gd0EQ09tZRnz/PpVdLwvp/ufMtJ1iDFYddDaPpZXKqPyaxfYBLs3ueiaksQ26GGa7sci0OqFzNs7KA==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "eslint-scope-5.1.1" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-5.1.1.tgz";
        sha512 = "2NxwbF/hZ0KpepYN0cNbo+FN6XoK7GaHlQhgx/hIZl6Va0bF45RQOOwhLIy8lQDbuCiadSLCBnH2CFYquit5bw==";
      };
    };
    "esrecurse-4.3.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.3.0.tgz";
        sha512 = "KmfKL3b6G+RXvP8N1vr3Tq1kL/oCFgn2NYXEtqP8/L3pKapUA4G8cFVaoF3SU323CD4XypR/ffioHmkti6/Tag==";
      };
    };
    "estraverse-4.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.3.0.tgz";
        sha512 = "39nnKffWz8xN1BU/2c79n9nB9HDzo0niYUqx6xyqUnyoAnQyyWpOTdZEeiCch8BBu515t4wp9ZmgVfVhn9EBpw==";
      };
    };
    "estraverse-5.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz";
        sha512 = "MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "events-3.3.0" = {
      name = "events";
      packageName = "events";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
        sha512 = "mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "follow-redirects-1.15.0" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.0.tgz";
        sha512 = "aExlJShTV4qOUOL7yF1U5tvLCB0xQuudbf6toyYA0E/acBNw71mvjFTnLaRp50aQaYocMR0a/RMMBIHeZnGyjQ==";
      };
    };
    "form-data-4.0.0" = {
      name = "form-data";
      packageName = "form-data";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz";
        sha512 = "ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "glob-to-regexp-0.4.1" = {
      name = "glob-to-regexp";
      packageName = "glob-to-regexp";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-to-regexp/-/glob-to-regexp-0.4.1.tgz";
        sha512 = "lkX1HJXwyMcprw/5YUZc2s7DrpAiHB21/V+E1rHUrVNokkvB6bqMzT0VfV6/86ZNabt1k14YOIaT7nDvOX3Iiw==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-core-module-2.9.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.9.0.tgz";
        sha512 = "+5FPy5PnwmO3lvfMb0AsoPaBG+5KHUI0wYFXOtYPnVVVspTFUuMZNfNaNVRt3FZadstu2c8x23vykRW/NBoU6A==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "javascript-natural-sort-0.7.1" = {
      name = "javascript-natural-sort";
      packageName = "javascript-natural-sort";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/javascript-natural-sort/-/javascript-natural-sort-0.7.1.tgz";
        sha1 = "f9e2303d4507f6d74355a73664d1440fb5a0ef59";
      };
    };
    "jest-worker-27.5.1" = {
      name = "jest-worker";
      packageName = "jest-worker";
      version = "27.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jest-worker/-/jest-worker-27.5.1.tgz";
        sha512 = "7vuh85V5cdDofPyxn58nrPjBktZo0u9x1g8WtjQol+jZDaE+fhN+cIvTj11GndBnMnyfrUOG1sZQxCdjKh+DKg==";
      };
    };
    "jmespath-0.16.0" = {
      name = "jmespath";
      packageName = "jmespath";
      version = "0.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jmespath/-/jmespath-0.16.0.tgz";
        sha512 = "9FzQjJ7MATs1tSpnco1K6ayiYE3figslrXA72G2HQ/n76RzvYlofyi5QM+iX4YRs/pu3yzxlVQSST23+dMDknw==";
      };
    };
    "js-cookie-3.0.1" = {
      name = "js-cookie";
      packageName = "js-cookie";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-cookie/-/js-cookie-3.0.1.tgz";
        sha512 = "+0rgsUXZu4ncpPxRL+lNEptWMOWl9etvPHc/koSRp6MPwpRYAhmk0dUG00J4bxVV3r9uUzfo24wW0knS07SKSw==";
      };
    };
    "json-parse-even-better-errors-2.3.1" = {
      name = "json-parse-even-better-errors";
      packageName = "json-parse-even-better-errors";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz";
        sha512 = "xyFwyhro/JEof6Ghe2iz2NcXoj2sloNsWr/XsERDK/oiPCfaNhl5ONfp+jQdAZRQQ0IJWNzH9zIZF7li91kh2w==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-source-map-0.6.1" = {
      name = "json-source-map";
      packageName = "json-source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-source-map/-/json-source-map-0.6.1.tgz";
        sha512 = "1QoztHPsMQqhDq0hlXY5ZqcEdUzxQEIxgFkKl4WUp2pgShObl+9ovi4kRh2TfvAfxAoHOJ9vIMEqk3k4iex7tg==";
      };
    };
    "json5-2.2.1" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.1.tgz";
        sha512 = "1hqLFMSrGHRHxav9q9gNjJ5EXznIxGVO09xQRrwplcS8qs28pZ8s8hupZAmqDwZUmVZ2Qb2jnyPOWcDH8m8dlA==";
      };
    };
    "jsoneditor-9.9.0" = {
      name = "jsoneditor";
      packageName = "jsoneditor";
      version = "9.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsoneditor/-/jsoneditor-9.9.0.tgz";
        sha512 = "NHJhyaqcc5U33ah6dEcd0S9b14Auocpe9nydvC9ui7Uq/vjEFnsd7ot6O9Jqwv53B7DmHFUWq5cT4qeWh4MEoA==";
      };
    };
    "jsonrepair-2.2.1" = {
      name = "jsonrepair";
      packageName = "jsonrepair";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonrepair/-/jsonrepair-2.2.1.tgz";
        sha512 = "o9Je8TceILo872uQC9fIBJm957j1Io7z8Ca1iWIqY6S5S65HGE9XN7XEEw7+tUviB9Vq4sygV89MVTxl+rhZyg==";
      };
    };
    "klona-2.0.5" = {
      name = "klona";
      packageName = "klona";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/klona/-/klona-2.0.5.tgz";
        sha512 = "pJiBpiXMbt7dkzXe8Ghj/u4FfXOOa98fPW+bihOJ4SjnoijweJrNThJfd3ifXpXhREjpoF2mZVH1GfS9LV3kHQ==";
      };
    };
    "loader-runner-4.3.0" = {
      name = "loader-runner";
      packageName = "loader-runner";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-runner/-/loader-runner-4.3.0.tgz";
        sha512 = "3R/1M+yS3j5ou80Me59j7F9IMs4PXs3VqRrm0TU3AbKPxlmpoY1TNscJV/oGJXo8qCatFGTfDbY6W6ipGOYXfg==";
      };
    };
    "loader-utils-2.0.2" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-2.0.2.tgz";
        sha512 = "TM57VeHptv569d/GKh6TAYdzKblwDNiumOdkFnejjD0XwTH87K90w3O7AiJRqdQoXygvi1VQTJTLGhJl7WqA7A==";
      };
    };
    "lodash.sortby-4.7.0" = {
      name = "lodash.sortby";
      packageName = "lodash.sortby";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.sortby/-/lodash.sortby-4.7.0.tgz";
        sha1 = "edd14c824e2cc9c1e0b0a1b42bb5210516a42438";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "magic-string-0.25.9" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.25.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.25.9.tgz";
        sha512 = "RmF0AsMzgt25qzqqLc1+MbHmhdx0ojF2Fvs4XnOqz2ZOBXzzkEwc/dJQZCYHAn7v1jbVOjAZfK8msRn4BxO4VQ==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "mobius1-selectr-2.4.13" = {
      name = "mobius1-selectr";
      packageName = "mobius1-selectr";
      version = "2.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/mobius1-selectr/-/mobius1-selectr-2.4.13.tgz";
        sha512 = "Mk9qDrvU44UUL0EBhbAA1phfQZ7aMZPjwtL7wkpiBzGh8dETGqfsh50mWoX9EkjDlkONlErWXArHCKfoxVg0Bw==";
      };
    };
    "nanoid-3.3.4" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.4.tgz";
        sha512 = "MqBkQh/OHTS2egovRtLk45wEyNXwF+cokD+1YPf9u5VfJiRdAiRwB2froX5Co9Rh20xs4siNPm8naNotSD6RBw==";
      };
    };
    "neo-async-2.6.2" = {
      name = "neo-async";
      packageName = "neo-async";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo-async/-/neo-async-2.6.2.tgz";
        sha512 = "Yd3UES5mWCSqR+qNT93S3UoYUkqAZ9lLg8a7g9rimsWmYGK8cVToA4/sF3RrshdyV3sAGMXVUmpMYOw+dLpOuw==";
      };
    };
    "node-releases-2.0.4" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.4.tgz";
        sha512 = "gbMzqQtTtDz/00jQzZ21PQzdI9PyLYqUSvD0p3naOhX4odFji0ZxYdnVwPTxmSwkmxhcFImpozceidSG+AgoPQ==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "picomodal-3.0.0" = {
      name = "picomodal";
      packageName = "picomodal";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomodal/-/picomodal-3.0.0.tgz";
        sha1 = "facd30f4fbf34a809c1e04ea525f004f399c0b82";
      };
    };
    "postcss-8.4.13" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.13.tgz";
        sha512 = "jtL6eTBrza5MPzy8oJLFuUscHDXTV5KcLlqAWHl5q5WYRfnNRGSmOZmOZ1T6Gy7A99mOZfqungmZMpMmCVJ8ZA==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "quasar-2.7.3" = {
      name = "quasar";
      packageName = "quasar";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/quasar/-/quasar-2.7.3.tgz";
        sha512 = "4YQQP1FbfshXwav9QcOHpvSg4eME4iKzd85m4562EqcfuhRtycC/2WQg+cRxlEr43gEHM0uXaJmybNUWZpoYkw==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "resolve-1.22.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.0.tgz";
        sha512 = "Hhtrw0nLeSrFQ7phPp4OOcVjLPIeMnRlr5mcnVuMe7M/7eBn98A3hmFRLoFo3DLZkivSYwhRUJTyPyWAk56WLw==";
      };
    };
    "rollup-2.72.1" = {
      name = "rollup";
      packageName = "rollup";
      version = "2.72.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-2.72.1.tgz";
        sha512 = "NTc5UGy/NWFGpSqF1lFY8z9Adri6uhyMLI6LvPAXdBKoPRFhIIiBUpt+Qg2awixqO3xvzSijjhnb4+QEZwJmxA==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sass-1.32.0" = {
      name = "sass";
      packageName = "sass";
      version = "1.32.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.32.0.tgz";
        sha512 = "fhyqEbMIycQA4blrz/C0pYhv2o4x2y6FYYAH0CshBw3DXh5D5wyERgxw0ptdau1orc/GhNrhF7DFN2etyOCEng==";
      };
    };
    "sass-loader-10.2.1" = {
      name = "sass-loader";
      packageName = "sass-loader";
      version = "10.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass-loader/-/sass-loader-10.2.1.tgz";
        sha512 = "RRvWl+3K2LSMezIsd008ErK4rk6CulIMSwrcc2aZvjymUgKo/vjXGp1rSWmfTUX7bblEOz8tst4wBwWtCGBqKA==";
      };
    };
    "schema-utils-3.1.1" = {
      name = "schema-utils";
      packageName = "schema-utils";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/schema-utils/-/schema-utils-3.1.1.tgz";
        sha512 = "Y5PQxS4ITlC+EahLuXaY86TXfR7Dc5lw294alXOq86JAHCihAIZfqv8nNCWvaEJvaC51uN9hbLGeV0cFBdH+Fw==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "serialize-javascript-6.0.0" = {
      name = "serialize-javascript";
      packageName = "serialize-javascript";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialize-javascript/-/serialize-javascript-6.0.0.tgz";
        sha512 = "Qr3TosvguFt8ePWqsvRfrKyQXIiW+nGbYpy8XK24NQHE83caxWt+mIymTT19DGFbNWNLfEwsrkSmN64lVWB9ag==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.8.0-beta.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.8.0-beta.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.8.0-beta.0.tgz";
        sha512 = "2ymg6oRBpebeZi9UUNsgQ89bhx01TcTkmNTGnNO88imTmbSgy4nfujrgVEFKWpMTEGA11EDkTt7mqObTPdigIA==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "svg.draggable.js-2.2.2" = {
      name = "svg.draggable.js";
      packageName = "svg.draggable.js";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.draggable.js/-/svg.draggable.js-2.2.2.tgz";
        sha512 = "JzNHBc2fLQMzYCZ90KZHN2ohXL0BQJGQimK1kGk6AvSeibuKcIdDX9Kr0dT9+UJ5O8nYA0RB839Lhvk4CY4MZw==";
      };
    };
    "svg.easing.js-2.0.0" = {
      name = "svg.easing.js";
      packageName = "svg.easing.js";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.easing.js/-/svg.easing.js-2.0.0.tgz";
        sha1 = "8aa9946b0a8e27857a5c40a10eba4091e5691f12";
      };
    };
    "svg.filter.js-2.0.2" = {
      name = "svg.filter.js";
      packageName = "svg.filter.js";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.filter.js/-/svg.filter.js-2.0.2.tgz";
        sha1 = "91008e151389dd9230779fcbe6e2c9a362d1c203";
      };
    };
    "svg.js-2.7.1" = {
      name = "svg.js";
      packageName = "svg.js";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.js/-/svg.js-2.7.1.tgz";
        sha512 = "ycbxpizEQktk3FYvn/8BH+6/EuWXg7ZpQREJvgacqn46gIddG24tNNe4Son6omdXCnSOaApnpZw6MPCBA1dODA==";
      };
    };
    "svg.pathmorphing.js-0.1.3" = {
      name = "svg.pathmorphing.js";
      packageName = "svg.pathmorphing.js";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.pathmorphing.js/-/svg.pathmorphing.js-0.1.3.tgz";
        sha512 = "49HWI9X4XQR/JG1qXkSDV8xViuTLIWm/B/7YuQELV5KMOPtXjiwH4XPJvr/ghEDibmLQ9Oc22dpWpG0vUDDNww==";
      };
    };
    "svg.resize.js-1.4.3" = {
      name = "svg.resize.js";
      packageName = "svg.resize.js";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.resize.js/-/svg.resize.js-1.4.3.tgz";
        sha512 = "9k5sXJuPKp+mVzXNvxz7U0uC9oVMQrrf7cFsETznzUDDm0x8+77dtZkWdMfRlmbkEEYvUn9btKuZ3n41oNA+uw==";
      };
    };
    "svg.select.js-2.1.2" = {
      name = "svg.select.js";
      packageName = "svg.select.js";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.select.js/-/svg.select.js-2.1.2.tgz";
        sha512 = "tH6ABEyJsAOVAhwcCjF8mw4crjXSI1aa7j2VQR8ZuJ37H2MBUbyeqYr5nEO7sSN3cy9AR9DUwNg0t/962HlDbQ==";
      };
    };
    "svg.select.js-3.0.1" = {
      name = "svg.select.js";
      packageName = "svg.select.js";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg.select.js/-/svg.select.js-3.0.1.tgz";
        sha512 = "h5IS/hKkuVCbKSieR9uQCj9w+zLHoPh+ce19bBYyqF53g6mnPB8sAtIbe1s9dh2S2fCmYX2xel1Ln3PJBbK4kw==";
      };
    };
    "tapable-2.2.1" = {
      name = "tapable";
      packageName = "tapable";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tapable/-/tapable-2.2.1.tgz";
        sha512 = "GNzQvQTOIP6RyTfE2Qxb8ZVlNmw0n88vp1szwWRimP02mnTsx3Wtn5qRdqY9w2XduFNUgvOwhNnQsjwCp+kqaQ==";
      };
    };
    "terser-5.13.1" = {
      name = "terser";
      packageName = "terser";
      version = "5.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-5.13.1.tgz";
        sha512 = "hn4WKOfwnwbYfe48NgrQjqNOH9jzLqRcIfbYytOXCOv46LBfWr9bDS17MQqOi+BWGD0sJK3Sj5NC/gJjiojaoA==";
      };
    };
    "terser-webpack-plugin-5.3.1" = {
      name = "terser-webpack-plugin";
      packageName = "terser-webpack-plugin";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-5.3.1.tgz";
        sha512 = "GvlZdT6wPQKbDNW/GDQzZFg/j4vKU96yl2q6mcUkzKOgW4gwf1Z8cZToUCrz31XHlPWH8MVb1r2tFtdDtTGJ7g==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tr46-1.0.1" = {
      name = "tr46";
      packageName = "tr46";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-1.0.1.tgz";
        sha1 = "a8b13fd6bfd2489519674ccde55ba3693b706d09";
      };
    };
    "typescript-4.6.4" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.6.4.tgz";
        sha512 = "9ia/jWHIEbo49HfjrLGfKbZSuWo9iTMwXO+Ca3pRsSpbsMbc7/IU8NKdCZVRRBafVPGnoJeFL76ZOAA84I9fEg==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "vanilla-picker-2.12.1" = {
      name = "vanilla-picker";
      packageName = "vanilla-picker";
      version = "2.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vanilla-picker/-/vanilla-picker-2.12.1.tgz";
        sha512 = "2qrEP9VYylKXbyzXKsbu2dferBTvqnlsr29XjHwFE+/MEp0VNj6oEUESLDtKZ7DWzGdSv1x/+ujqFZF+KsO3cg==";
      };
    };
    "vite-2.9.12" = {
      name = "vite";
      packageName = "vite";
      version = "2.9.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vite/-/vite-2.9.12.tgz";
        sha512 = "suxC36dQo9Rq1qMB2qiRorNJtJAdxguu5TMvBHOc/F370KvqAe9t48vYp+/TbPKRNrMh/J55tOUmkuIqstZaew==";
      };
    };
    "vue-3.2.37" = {
      name = "vue";
      packageName = "vue";
      version = "3.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue/-/vue-3.2.37.tgz";
        sha512 = "bOKEZxrm8Eh+fveCqS1/NkG/n6aMidsI6hahas7pa0w/l7jkbssJVsRhVDs07IdDq7h9KHswZOgItnwJAgtVtQ==";
      };
    };
    "vue-i18n-9.1.10" = {
      name = "vue-i18n";
      packageName = "vue-i18n";
      version = "9.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-i18n/-/vue-i18n-9.1.10.tgz";
        sha512 = "jpr7gV5KPk4n+sSPdpZT8Qx3XzTcNDWffRlHV/cT2NUyEf+sEgTTmLvnBAibjOFJ0zsUyZlVTAWH5DDnYep+1g==";
      };
    };
    "vue-router-4.0.16" = {
      name = "vue-router";
      packageName = "vue-router";
      version = "4.0.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-router/-/vue-router-4.0.16.tgz";
        sha512 = "JcO7cb8QJLBWE+DfxGUL3xUDOae/8nhM1KVdnudadTAORbuxIC/xAydC5Zr/VLHUDQi1ppuTF5/rjBGzgzrJNA==";
      };
    };
    "vue-tsc-0.38.1" = {
      name = "vue-tsc";
      packageName = "vue-tsc";
      version = "0.38.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-tsc/-/vue-tsc-0.38.1.tgz";
        sha512 = "jwR4uwTkjsYhAW8o/BvnkeZsariNoi2Y53XSqWIbjtj7X9Laob+qwC2iVuQyRymYdqbbiqqX+CxfPWtwLACXfg==";
      };
    };
    "vue3-apexcharts-1.4.1" = {
      name = "vue3-apexcharts";
      packageName = "vue3-apexcharts";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue3-apexcharts/-/vue3-apexcharts-1.4.1.tgz";
        sha512 = "96qP8JDqB9vwU7bkG5nVU+E0UGQn7yYQVqUUCLQMYWDuQyu2vE77H/UFZ1yI+hwzlSTBKT9BqnNG8JsFegB3eg==";
      };
    };
    "vuex-4.0.2" = {
      name = "vuex";
      packageName = "vuex";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vuex/-/vuex-4.0.2.tgz";
        sha512 = "M6r8uxELjZIK8kTKDGgZTYX/ahzblnzC4isU1tpmEuOIIKmV+TRdc+H4s8ds2NuZ7wpUTdGRzJRtoj+lI+pc0Q==";
      };
    };
    "watchpack-2.3.1" = {
      name = "watchpack";
      packageName = "watchpack";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/watchpack/-/watchpack-2.3.1.tgz";
        sha512 = "x0t0JuydIo8qCNctdDrn1OzH/qDzk2+rdCOC3YzumZ42fiMqmQ7T3xQurykYMhYfHaPHTp4ZxAx2NfUo1K6QaA==";
      };
    };
    "webidl-conversions-4.0.2" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-4.0.2.tgz";
        sha512 = "YQ+BmxuTgd6UXZW3+ICGfyqRyHXVlD5GtQr5+qjiNW7bF0cqrzX500HVXPBOvgXb5YnzDd+h0zqyv61KUD7+Sg==";
      };
    };
    "webpack-5.72.1" = {
      name = "webpack";
      packageName = "webpack";
      version = "5.72.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack/-/webpack-5.72.1.tgz";
        sha512 = "dXG5zXCLspQR4krZVR6QgajnZOjW2K/djHvdcRaDQvsjV9z9vaW6+ja5dZOYbqBBjF6kGXka/2ZyxNdc+8Jung==";
      };
    };
    "webpack-sources-3.2.3" = {
      name = "webpack-sources";
      packageName = "webpack-sources";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-sources/-/webpack-sources-3.2.3.tgz";
        sha512 = "/DyMEOrDgLKKIG0fmvtz+4dUX/3Ghozwgm6iPp8KRhvn+eQf9+Q7GWxVNMk3+uCPWfdXYC4ExGBckIXdFEfH1w==";
      };
    };
    "whatwg-url-7.1.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-7.1.0.tgz";
        sha512 = "WUu7Rg1DroM7oQvGWfOiAK21n74Gg+T4elXEQYkOhtyLeWiJFoOGLXPKI/9gzIie9CtwVLm8wtw6YJdKyxSjeg==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "zinc-search";
    packageName = "zinc-search";
    version = "0.2.4";
    src = ./.;
    dependencies = [
      sources."@babel/parser-7.18.5"
      sources."@intlify/core-base-9.1.10"
      sources."@intlify/devtools-if-9.1.10"
      sources."@intlify/message-compiler-9.1.10"
      sources."@intlify/message-resolver-9.1.10"
      sources."@intlify/runtime-9.1.10"
      sources."@intlify/shared-9.1.10"
      sources."@intlify/vue-devtools-9.1.10"
      sources."@quasar/extras-1.14.0"
      sources."@quasar/vite-plugin-1.0.10"
      sources."@sphinxxxx/color-conversion-2.2.2"
      sources."@types/eslint-8.4.2"
      sources."@types/eslint-scope-3.7.3"
      sources."@types/estree-0.0.51"
      sources."@types/js-cookie-3.0.2"
      sources."@types/json-schema-7.0.11"
      sources."@types/node-17.0.32"
      sources."@vitejs/plugin-vue-2.3.3"
      sources."@volar/code-gen-0.38.1"
      sources."@volar/source-map-0.38.1"
      sources."@volar/vue-code-gen-0.38.1"
      sources."@volar/vue-typescript-0.38.1"
      sources."@vue/compiler-core-3.2.37"
      sources."@vue/compiler-dom-3.2.37"
      sources."@vue/compiler-sfc-3.2.37"
      sources."@vue/compiler-ssr-3.2.37"
      sources."@vue/devtools-api-6.1.4"
      sources."@vue/reactivity-3.2.37"
      sources."@vue/reactivity-transform-3.2.37"
      sources."@vue/runtime-core-3.2.37"
      sources."@vue/runtime-dom-3.2.37"
      sources."@vue/server-renderer-3.2.37"
      sources."@vue/shared-3.2.37"
      sources."@webassemblyjs/ast-1.11.1"
      sources."@webassemblyjs/floating-point-hex-parser-1.11.1"
      sources."@webassemblyjs/helper-api-error-1.11.1"
      sources."@webassemblyjs/helper-buffer-1.11.1"
      sources."@webassemblyjs/helper-numbers-1.11.1"
      sources."@webassemblyjs/helper-wasm-bytecode-1.11.1"
      sources."@webassemblyjs/helper-wasm-section-1.11.1"
      sources."@webassemblyjs/ieee754-1.11.1"
      sources."@webassemblyjs/leb128-1.11.1"
      sources."@webassemblyjs/utf8-1.11.1"
      sources."@webassemblyjs/wasm-edit-1.11.1"
      sources."@webassemblyjs/wasm-gen-1.11.1"
      sources."@webassemblyjs/wasm-opt-1.11.1"
      sources."@webassemblyjs/wasm-parser-1.11.1"
      sources."@webassemblyjs/wast-printer-1.11.1"
      sources."@xtuc/ieee754-1.2.0"
      sources."@xtuc/long-4.2.2"
      sources."ace-builds-1.6.0"
      sources."acorn-8.7.1"
      sources."acorn-import-assertions-1.8.0"
      sources."ajv-6.12.6"
      sources."ajv-keywords-3.5.2"
      sources."anymatch-3.1.2"
      sources."apexcharts-3.35.3"
      sources."asynckit-0.4.0"
      sources."axios-0.27.2"
      sources."base64-js-1.5.1"
      sources."big.js-5.2.2"
      sources."binary-extensions-2.2.0"
      sources."braces-3.0.2"
      sources."browserslist-4.20.3"
      sources."buffer-6.0.3"
      sources."buffer-from-1.1.2"
      sources."caniuse-lite-1.0.30001340"
      sources."chokidar-3.5.3"
      sources."chrome-trace-event-1.0.3"
      sources."combined-stream-1.0.8"
      sources."commander-2.20.3"
      sources."csstype-2.6.20"
      sources."delayed-stream-1.0.0"
      sources."electron-to-chromium-1.4.137"
      sources."emojis-list-3.0.0"
      sources."enhanced-resolve-5.9.3"
      sources."es-module-lexer-0.9.3"
      sources."esbuild-0.14.39"
      sources."esbuild-android-64-0.14.39"
      sources."esbuild-android-arm64-0.14.39"
      sources."esbuild-darwin-64-0.14.39"
      sources."esbuild-darwin-arm64-0.14.39"
      sources."esbuild-freebsd-64-0.14.39"
      sources."esbuild-freebsd-arm64-0.14.39"
      sources."esbuild-linux-32-0.14.39"
      sources."esbuild-linux-64-0.14.39"
      sources."esbuild-linux-arm-0.14.39"
      sources."esbuild-linux-arm64-0.14.39"
      sources."esbuild-linux-mips64le-0.14.39"
      sources."esbuild-linux-ppc64le-0.14.39"
      sources."esbuild-linux-riscv64-0.14.39"
      sources."esbuild-linux-s390x-0.14.39"
      sources."esbuild-netbsd-64-0.14.39"
      sources."esbuild-openbsd-64-0.14.39"
      sources."esbuild-sunos-64-0.14.39"
      sources."esbuild-windows-32-0.14.39"
      sources."esbuild-windows-64-0.14.39"
      sources."esbuild-windows-arm64-0.14.39"
      sources."escalade-3.1.1"
      sources."eslint-scope-5.1.1"
      (sources."esrecurse-4.3.0" // {
        dependencies = [
          sources."estraverse-5.3.0"
        ];
      })
      sources."estraverse-4.3.0"
      sources."estree-walker-2.0.2"
      sources."events-3.3.0"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fill-range-7.0.1"
      sources."follow-redirects-1.15.0"
      sources."form-data-4.0.0"
      sources."fsevents-2.3.2"
      sources."function-bind-1.1.1"
      sources."glob-parent-5.1.2"
      sources."glob-to-regexp-0.4.1"
      sources."graceful-fs-4.2.10"
      sources."has-1.0.3"
      sources."has-flag-4.0.0"
      sources."ieee754-1.2.1"
      sources."is-binary-path-2.1.0"
      sources."is-core-module-2.9.0"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."javascript-natural-sort-0.7.1"
      sources."jest-worker-27.5.1"
      sources."jmespath-0.16.0"
      sources."js-cookie-3.0.1"
      sources."json-parse-even-better-errors-2.3.1"
      sources."json-schema-traverse-0.4.1"
      sources."json-source-map-0.6.1"
      sources."json5-2.2.1"
      sources."jsoneditor-9.9.0"
      sources."jsonrepair-2.2.1"
      sources."klona-2.0.5"
      sources."loader-runner-4.3.0"
      sources."loader-utils-2.0.2"
      sources."lodash.sortby-4.7.0"
      sources."lru-cache-6.0.0"
      sources."magic-string-0.25.9"
      sources."merge-stream-2.0.0"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."mobius1-selectr-2.4.13"
      sources."nanoid-3.3.4"
      sources."neo-async-2.6.2"
      sources."node-releases-2.0.4"
      sources."normalize-path-3.0.0"
      sources."path-parse-1.0.7"
      sources."picocolors-1.0.0"
      sources."picomatch-2.3.1"
      sources."picomodal-3.0.0"
      sources."postcss-8.4.13"
      sources."punycode-2.1.1"
      sources."quasar-2.7.3"
      sources."randombytes-2.1.0"
      sources."readdirp-3.6.0"
      sources."resolve-1.22.0"
      sources."rollup-2.72.1"
      sources."safe-buffer-5.2.1"
      sources."sass-1.32.0"
      sources."sass-loader-10.2.1"
      sources."schema-utils-3.1.1"
      sources."semver-7.3.7"
      sources."serialize-javascript-6.0.0"
      sources."source-map-0.6.1"
      sources."source-map-js-1.0.2"
      sources."source-map-support-0.5.21"
      sources."sourcemap-codec-1.4.8"
      sources."supports-color-8.1.1"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."svg.draggable.js-2.2.2"
      sources."svg.easing.js-2.0.0"
      sources."svg.filter.js-2.0.2"
      sources."svg.js-2.7.1"
      sources."svg.pathmorphing.js-0.1.3"
      (sources."svg.resize.js-1.4.3" // {
        dependencies = [
          sources."svg.select.js-2.1.2"
        ];
      })
      sources."svg.select.js-3.0.1"
      sources."tapable-2.2.1"
      (sources."terser-5.13.1" // {
        dependencies = [
          sources."source-map-0.8.0-beta.0"
        ];
      })
      sources."terser-webpack-plugin-5.3.1"
      sources."to-regex-range-5.0.1"
      sources."tr46-1.0.1"
      sources."typescript-4.6.4"
      sources."uri-js-4.4.1"
      sources."vanilla-picker-2.12.1"
      sources."vite-2.9.12"
      sources."vue-3.2.37"
      sources."vue-i18n-9.1.10"
      sources."vue-router-4.0.16"
      sources."vue-tsc-0.38.1"
      sources."vue3-apexcharts-1.4.1"
      sources."vuex-4.0.2"
      sources."watchpack-2.3.1"
      sources."webidl-conversions-4.0.2"
      sources."webpack-5.72.1"
      sources."webpack-sources-3.2.3"
      sources."whatwg-url-7.1.0"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A web console for Zinc";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
